In [31]:
person = {
    "name": "John", 
    "years": 32, 
    "weight": "50kg"
}

In [32]:
import pandas as pd
import numpy as np

data = {
    "name": ["Ada", "Grace", "Alan", "Rosalind"],    
    "age": [36, 85, 41, 37],    
    "field": ["Math", "CS", "CS", "Chemistry"], 
}

In [33]:
df = pd.DataFrame(data)

In [34]:
df

       name  age      field
0       Ada   36       Math
1     Grace   85         CS
2      Alan   41         CS
3  Rosalind   37  Chemistry

# Inpsecting Data

In [35]:
#By default it gives five records but if a number is passed in it gives according to the number entered.
df.head()

       name  age      field
0       Ada   36       Math
1     Grace   85         CS
2      Alan   41         CS
3  Rosalind   37  Chemistry

In [36]:
# df["age"][0] = None

In [37]:
df.head()

       name  age      field
0       Ada   36       Math
1     Grace   85         CS
2      Alan   41         CS
3  Rosalind   37  Chemistry

In [38]:
df.head(3)

    name  age field
0    Ada   36  Math
1  Grace   85    CS
2   Alan   41    CS

#By default it gives the last five records

In [39]:
df.tail()

       name  age      field
0       Ada   36       Math
1     Grace   85         CS
2      Alan   41         CS
3  Rosalind   37  Chemistry

In [40]:
df.tail(2)

       name  age      field
2      Alan   41         CS
3  Rosalind   37  Chemistry

#Gives us details about the data

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      object
 1   age     4 non-null      int64
 2   field   4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

#Gives descriptive statistics about the data

In [42]:
df.describe()

             age
count   4.000000
mean   49.750000
std    23.599082
min    36.000000
25%    36.750000
50%    39.000000
75%    52.000000
max    85.000000

In [43]:
df

       name  age      field
0       Ada   36       Math
1     Grace   85         CS
2      Alan   41         CS
3  Rosalind   37  Chemistry

### Selecting and Slicing Data sets

In [51]:
df_copy = df.copy()

In [52]:
df_copy.describe()

             age
count   4.000000
mean   49.750000
std    23.599082
min    36.000000
25%    36.750000
50%    39.000000
75%    52.000000
max    85.000000

#Selecting Columns

In [46]:
df_copy["name"]

0         Ada
1       Grace
2        Alan
3    Rosalind
Name: name, dtype: object

In [47]:
df_copy["age"]

0    36
1    85
2    41
3    37
Name: age, dtype: int64

#Finding the sum of a numeric column
df_copy["age"].sum()

In [48]:
df_copy["age"].max()

85

#Selecting Multiple Columns

In [49]:
df_copy[["age","name"]]

   age      name
0   36       Ada
1   85     Grace
2   41      Alan
3   37  Rosalind

In [50]:
df_copy[["name","age"]]

       name  age
0       Ada   36
1     Grace   85
2      Alan   41
3  Rosalind   37