# Sales Data Analysis Assessment

Welcome to your Python and Pandas assessment! In this notebook, you will work with a dataset of sales records stored in a Python dictionary. Follow the instructions in each section and write the required code to complete the analysis.

## Part 1: Dataset Setup

Run the cell below to load the sales data dictionary into your workspace.

In [1]:
# Sales data containing 50 records
sales_data = {
    'Transaction_ID': [f'TXN{i:03d}' for i in range(1, 51)],
    'Date': [
        '2026-01-01', '2026-01-01', '2026-01-02', '2026-01-02', '2026-01-03',
        '2026-01-03', '2026-01-04', '2026-01-04', '2026-01-05', '2026-01-05',
        '2026-01-06', '2026-01-06', '2026-01-07', '2026-01-07', '2026-01-08',
        '2026-01-08', '2026-01-09', '2026-01-09', '2026-01-10', '2026-01-10',
        '2026-01-11', '2026-01-11', '2026-01-12', '2026-01-12', '2026-01-13',
        '2026-01-13', '2026-01-14', '2026-01-14', '2026-01-15', '2026-01-15',
        '2026-01-16', '2026-01-16', '2026-01-17', '2026-01-17', '2026-01-18',
        '2026-01-18', '2026-01-19', '2026-01-19', '2026-01-20', '2026-01-20',
        '2026-01-21', '2026-01-21', '2026-01-22', '2026-01-22', '2026-01-23',
        '2026-01-23', '2026-01-24', '2026-01-24', '2026-01-25', '2026-01-25'
    ],
    'Region': ['North', 'South', 'East', 'West', 'Central', 'North', 'South', 'East', 'West', 'Central'] * 5,
    'Category': ['Electronics', 'Clothing', 'Furniture', 'Electronics', 'Office Supplies'] * 10,
    'Quantity': [
        3, 1, 5, 2, 4, 2, 6, 1, 3, 5,
        2, 4, 1, 3, 2, 5, 1, 4, 2, 3,
        5, 2, 1, 4, 3, 2, 6, 1, 4, 3,
        2, 5, 1, 3, 4, 2, 1, 5, 3, 2,
        4, 1, 3, 2, 5, 3, 2, 4, 1, 6
    ],
    'Unit_Price': [
        120.50, 45.00, 300.00, 150.00, 25.50,
        120.50, 22.00, 310.00, 145.00, 30.00,
        500.00, 55.00, 150.00, 85.00, 25.50,
        110.00, 45.00, 290.00, 160.00, 28.00,
        520.00, 40.00, 300.00, 90.00, 22.00,
        130.00, 60.00, 320.00, 155.00, 35.00,
        490.00, 50.00, 140.00, 80.00, 26.00,
        125.00, 45.00, 310.00, 150.00, 29.00,
        510.00, 42.00, 295.00, 95.00, 24.00,
        135.00, 58.00, 330.00, 145.00, 32.00
    ],
    'Salesperson': ['Alice', 'Bob', 'Charlie', 'Diana', 'Evan'] * 10
}

## Part 2: Data Exploration & Preparation

### Exercise 1
Convert the `sales_data` dictionary into a Pandas DataFrame and display the first 5 rows of the DataFrame.

In [2]:
# Write your code below to create the DataFrame and display the head
import pandas as pd

# df = pd.DataFrame(...)

In [12]:
df = pd.DataFrame(sales_data)
df.head(5)

,Transaction_ID,Date,Region,Category,Quantity,Unit_Price,Salesperson
0,TXN001,2026-01-01,North,Electronics,3,120.5,Alice
1,TXN002,2026-01-01,South,Clothing,1,45.0,Bob
2,TXN003,2026-01-02,East,Furniture,5,300.0,Charlie
3,TXN004,2026-01-02,West,Electronics,2,150.0,Diana
4,TXN005,2026-01-03,Central,Office Supplies,4,25.5,Evan

### Exercise 2
Check the DataFrame for data types and missing values.

In [13]:
# Write your code below

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Transaction_ID  50 non-null     object
 1   Date            50 non-null     object
 2   Region          50 non-null     object
 3   Category        50 non-null     object
 4   Quantity        50 non-null     int64
 5   Unit_Price      50 non-null     float64
 6   Salesperson     50 non-null     object
dtypes: float64(1), int64(1), object(5)
memory usage: 2.9+ KB

In [15]:
df.isna().sum()

Transaction_ID    0
Date              0
Region            0
Category          0
Quantity          0
Unit_Price        0
Salesperson       0
dtype: int64

### Exercise 3
Create a new column in the DataFrame named `Total_Sales` which is calculated by multiplying `Quantity` by `Unit_Price`. Display the updated DataFrame.

In [19]:
# Write your code below

df["Total_Sales"] = df['Quantity'] * df['Unit_Price']
df.head()

,Transaction_ID,Date,Region,Category,Quantity,Unit_Price,Salesperson,Total_Sales
0,TXN001,2026-01-01,North,Electronics,3,120.5,Alice,361.5
1,TXN002,2026-01-01,South,Clothing,1,45.0,Bob,45.0
2,TXN003,2026-01-02,East,Furniture,5,300.0,Charlie,1500.0
3,TXN004,2026-01-02,West,Electronics,2,150.0,Diana,300.0
4,TXN005,2026-01-03,Central,Office Supplies,4,25.5,Evan,102.0

## Part 3: Aggregations & Calculations

### Exercise 4
Find the sum of total sales across all transactions.

In [21]:
# Write your code below
df["Total_Sales"].sum()

np.float64(22004.5)

### Exercise 5
Calculate the average unit price and the total quantity of items sold.

In [30]:
# Write your code below

def sum_average(data, col_1, col_2):
    _total_qty = data[col_1].sum() 
    _count = data[col_2].count()
    _average_unit_price = data[col_2].sum()/_count
    return f"AVERAGE UNIT PRICE: {_average_unit_price}, TOTAL QTY: {_total_qty}"
sum_average(df, "Quantity", "Unit_Price")

'AVERAGE UNIT PRICE: 150.0, TOTAL QTY: 149'

## Part 4: Grouping & Filtering

### Exercise 6
Group the data by `Region` and calculate the total sales for each region.

In [36]:
# Write your code below

regional_sales = df.groupby("Region")["Total_Sales"].sum()

regional_sales

Region
Central    1032.0
East       7635.0
North      8687.5
South      1335.0
West       3315.0
Name: Total_Sales, dtype: float64

### Exercise 7
Filter the DataFrame to show only the transactions where the `Category` is 'Electronics'.

In [40]:
# Write your code below

df[df["Category"] == 'Electronics'].head(5)

,Transaction_ID,Date,Region,Category,Quantity,Unit_Price,Salesperson,Total_Sales
0,TXN001,2026-01-01,North,Electronics,3,120.5,Alice,361.5
3,TXN004,2026-01-02,West,Electronics,2,150.0,Diana,300.0
5,TXN006,2026-01-03,North,Electronics,2,120.5,Alice,241.0
8,TXN009,2026-01-05,West,Electronics,3,145.0,Diana,435.0
10,TXN011,2026-01-06,North,Electronics,2,500.0,Alice,1000.0

### Exercise 8
Find out which salesperson generated the highest total sales.

In [46]:
# Write your code below

df_sorted = df.sort_values(by='Total_Sales', ascending=False)
df_sorted.head(1)["Salesperson"]

20    Alice
Name: Salesperson, dtype: object